const DefCountries = [
  {
    name: "Ukraine",
    capital: "Kiev",
    currency: "Ukrainian hryvnia",
    region: "Europe",
    flag: "https://restcountries.eu/data/ukr.svg",
    cioc: "UA",
    numericCode: "804",
    callingCodes: ["380"],
  },
  {
    name: "Ireland",
    capital: "Dublin",
    currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/irl.svg",
    cioc: "IE",
    numericCode: "372",
    callingCodes: ["353"],
  },
  {
    name: "Cook Islands",
    capital: "Avaure",
    currency: "New Zealand Dollar",
    region: "Oceaina",
    flag: "https://restcountries.eu/data/cok.svg",
    cioc: "CK",
    numericCode: "184",
    callingCodes: ["682"],
  },
  {
    name: "Germany",
    capital: "Berlin",
    currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/deu.svg",
    cioc: "DE",
    numericCode: "276",
    callingCodes: ["49"],
  },
  {
    name: "Turkey",
    capital: "Ankara",
    currency: "Turkish Lira",
    region: "Asia",
    flag: "https://restcountries.eu/data/tur.svg",
    cioc: "TR",
    numericCode: "792",
    callingCodes: ["90"],
  },
  {
    name: "Azerbaijan",
    capital: "Baku",
    currency: "Azerbaijani Manat",
    region: "Asia",
    flag: "https://restcountries.eu/data/aze.svg",
    cioc: "AZ",
    numericCode: "031",
    callingCodes: ["994"],
  },
  {
    name: "Netherlands",
    capital: "Amsterdam",
    currency: "Euro",
    region: "Europe",
    flag: "https://restcountries.eu/data/nld.svg",
    cioc: "NL",
    numericCode: "528",
    callingCodes: ["31"],
  },
  {
    name: "South Africa",
    capital: "Pretoria",
    currency: "South African Rand",
    region: "Africa",
    flag: "https://restcountries.eu/data/zaf.svg",
    cioc: "ZA",
    numericCode: "710",
    callingCodes: ["27"],
  },
  {
    name: "Norway",
    capital: "Oslo",
    currency: "Norwegian Krone",
    region: "Europe",
    flag: "https://restcountries.eu/data/nor.svg",
    cioc: "NO",
    numericCode: "578",
    callingCodes: ["47"],
  },
];

export default DefCountries;
